spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/synclife_db
    username: synclife_user
    password: synclife_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect